language: objective-c
osx_image: xcode8
xcode_project: TexLegeEngine.xcodeproj
xcode_scheme: TexLegeEngine-iOS
xcode_sdk: iphonesimulator10.0
env:
  global:
    - FRAMEWORK_NAME=TexLegeEngine
before_install:
    - brew update || true
#    - brew install xctool || true
#    - brew upgrade xctool || true
    - brew install carthage || true
#    - brew upgrade carthage || true
notifications:
    email:
        on_success: change
        on_failure: always
#before_script:
#    - carthage update --toolchain com.apple.dt.toolchain.Swift_2_3 --platform ios --no-build --derived-data ./Builds
#    - carthage bootstrap --no-build
#before_deploy:
#    - carthage build --toolchain com.apple.dt.toolchain.Swift_2_3 --platform ios --no-skip-current --derived-data ./Builds
#    - carthage archive $FRAMEWORK_NAME
script: 
    - bin/setup
    - xcrun xcodebuild test -project TexLegeEngine.xcodeproj -scheme TexLegeEngine-iOS -derivedDataPath ./Builds -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=10.0'

