language: objective-c
osx_image: xcode7.2
xcode_project: TexLegeEngine.xcodeproj
xcode_scheme: TexLegeEngine-iOS
xcode_sdk: iphonesimulator9.2
env:
  global:
    - FRAMEWORK_NAME=TexLegeEngine
before_install:
    - brew update || true
    - brew install xctool || true
    - brew upgrade xctool || true
    - brew install carthage || true
    - brew upgrade carthage || true
notifications:
    email:
        on_success: change
        on_failure: always
before_script:
    - carthage bootstrap --no-build
before_deploy:
    - carthage build --no-skip-current --platform iOS
    - carthage archive $FRAMEWORK_NAME
script: 
    - bin/setup
    - xctool -sdk iphonesimulator -scheme TexLegeEngine-iOS test 

